version: '3.7'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    container_name: nginx
    ports:
      - 8090:8090
    networks:
      - chat
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017 # output:input
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - ./data/mongo:/data/db
    networks:
      - chat
  chat-server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: chat-server
    environment:
      - PORT=8091
      - GIN_MODE=release
    volumes:
      - .:/app
    command: /main
    depends_on:
      - mongo
      - nginx
    networks:
      - chat
networks:
  chat:
    driver: bridge