# using data source Redis
version: '3.7'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    container_name: nginx
    ports:
      - 8090:8090 # output:input
    networks:
      - chat
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    image: redis:7-alpine
    restart: always
    container_name: redis-container
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/conf/redis.conf
    ports:
      - 6379:6379
    networks:
      - chat
  chat-server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: chat-server
    environment:
      PORT: 8091
      GIN_MODE: debug
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 8091:8091
    volumes:
      - .:/app
    command: /main
    depends_on:
      - redis
      - nginx
    networks:
      - chat
networks:
  chat:
    driver: bridge